# Workshop 1 Answer Key

In [1]:
import numpy as np

## Numpy Arrays

In order to implement a Neural Network, we will need a convenient way to perform matrix operations. 

Thankfully, Numpy provides a simple way to create and work with matrices, in the form ndarrays (n-dimensional arrays). We can use ndarrays to represent vectors, matrices, or even tensors (higher dimensional matrices). Before we get into creating a Neural Network, let's briefly learn the basics of ndarrays. We'll start by creating a simple array.

In [2]:
A = np.array([1, 2, 3, 4])

print(A)

[1 2 3 4]


Remember, we can think of ndarrays similarly to the way we think of matrices or vectors. What do you think are the dimensions of A? Is it 4 x 1? Something else? Discuss among your group.

In [3]:
# We can find the dimensions of A like so:
dim_A = A.shape

print("Dimensions of A: " + str(dim_A))

Dimensions of A: (4,)


As it turns out, A is neither 1 x 4 or 4 x 1. Instead, it is a one-dimensional array, or flattened array, of dimenson 4. Whenever we want to represent vectors in Numpy, we will use one-dimensional arrays. For operations like matrix multiplication, a one-dimensional array can fulfill the role of either a 4 x 1 or 1 x 4 matrix, so they are quite versatile.

You can index into one-dimensional arrays to grab individual indices or slices. You can also modify entries of arrays:

In [4]:
x = A[0]
print(x)

a_slice = A[1:3]
print(a_slice)

print("Before modifying: {}".format(A))
A[2] = 7
print("After modifying: {}".format(A))

1
[2 3]
Before modifying: [1 2 3 4]
After modifying: [1 2 7 4]


Let's make another array.

In [5]:
B = np.array([ [1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12],
               [13, 14, 15, 16] ])

print(B)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


What are the dimensions of B? Find the dimensions and print them below.

In [6]:
### TODO: print the dimensions of B below

print(B.shape)

###

(4, 4)


B is a two-dimensional array. These are useful for representing matrices, and they behave similarly to matrices in consideration to most operations.

We can also index into two-dimensional arrays. However, we have more options, as there are two dimensions of indices to index into as opposed to one. Look at some of the following examples:

In [7]:
y = B[0, 2]
print("A single entry: {}".format(y))

column1 = B[:, 0]
print("The first column: {}".format(column1))

row1 = B[0, :]
row2 = B[1]    # we can opt to leave out the second index, numpy will fetch everything in the 2nd dimension
print("The first row: {}".format(row1))
print("The second row: {}".format(row2))

crop = B[0:2, 1:3]
print("A crop from B:\n{}".format(crop))

A single entry: 3
The first column: [ 1  5  9 13]
The first row: [1 2 3 4]
The second row: [5 6 7 8]
A crop from B:
[[2 3]
 [6 7]]


In [8]:
### TODO: print one slice containing the last three entries of the third column of B

print(B[1:, 2])

###

[ 7 11 15]


Observe that indexing individual entries will yield scalars; indexing rows or columns will yield one-dimensional arrays; and indexing crops or submatrices will yield a two-dimensional array.

We see that scalar entries make up one-dimensional arrays, which can then be used to make up two-dimensional arrays. It is also true that two-dimensional arrays can be used to make up three-dimensional arrays. In general, n-dimensional arrays can be thought of as a collection of (n - 1)-dimensional arrays.

We can represent matrix multiplication and matrix-vector multiplication with np.dot().

In [9]:
right_product = np.dot(A, B)
print(right_product)
print()

left_product = np.dot(B, A)
print(left_product)

[126 140 154 168]

[ 42  98 154 210]


Similar to matrix multiplication, the order in which you enter arguments into np.dot() is very important.

In [10]:
### TODO: Print out the matrix product between the upper-leftmost 3 x 3 crop of B and the 
###       lower-rightmost 3 x 3 crop of B.
###       Then, replace the upper-rightmost 3 x 3 section of B with that product, and print B.

product = B[0:3, 0:3] @ B[1:4, 1:4]
print(product)

B[0:3, 1:4] = product
print(B)

###

[[ 68  74  80]
 [188 206 224]
 [308 338 368]]
[[  1  68  74  80]
 [  5 188 206 224]
 [  9 308 338 368]
 [ 13  14  15  16]]


There are many ways to instantiate ndarrays in numpy. Here are two common ways:

In [11]:
zero_array = np.zeros((2, 2))
print(zero_array)
print()

random_array = np.random.rand(4, 3)  # fills array with values between 0 and 1
print(random_array)

[[0. 0.]
 [0. 0.]]

[[0.6012382  0.74348489 0.83962783]
 [0.97865506 0.7966632  0.3733905 ]
 [0.47891023 0.25816803 0.65228563]
 [0.54221673 0.5477541  0.91071657]]


Both of these ways of instantiating arrays involve entering the desired dimensions into their respective functions. However, np.zeros() requires the dimensions to be contained inside parentheses, while np.random.rand() wants the dimensions to be entered as separate arguments. These small details are always difficult to remember, so you may often have to refer to the [numpy documentation](https://docs.scipy.org/doc/numpy/reference/index.html "Numpy Documentation").

In [12]:
### TODO: Constuct a random 5 x 4 array. Matrix multiply (use np.dot()) this with B and then print the result.
###       Remember, order matters!

C = np.random.rand(5, 4)
print(C @ B)

###

[[ 10.74416854 291.34667634 319.167852   346.98902765]
 [ 13.85618446 443.56735228 485.96134125 528.35533022]
 [ 13.06618431 300.83644146 329.17386613 357.5112908 ]
 [  8.34807815 136.04838673 148.85303117 161.6576756 ]
 [ 11.32138133 263.50176435 288.54230262 313.58284089]]
